name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run simple_example.py
      run: python simple_example.py <<< "World"

    - name: Run file_example.py
      run: python file_example.py

    - name: Run csv_example.py
      run: python csv_example.py
